manifest = "aaa3ba0920d093cb96c72b7af50db55ab329ac2ed6c31a237360a995ccf00525"

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
target = "//:concept_check"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.55.0" ]
revision = "daef1bad4a26308638ab709870b9542379bb8ad1"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.55.0" ]
revision = "892598f066f15a4b8352bbd6b5f2b1a90e12e6fc"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.55.0" ]
revision = "8fe65abe2334e0d84c2cba4c768ec2f2360b33e1"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.55.0" ]
revision = "17efc70a43f3d9379475b9637855b2be09da3bcd"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.55.0" ]
revision = "8dcbb4d4610e05a948704c47898a34c4fee827cb"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.55.0" ]
revision = "a41bc5546421204bda9a1572a75474b7197559b2"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.55.0" ]
revision = "e14d6eb7ed4f944d0c0bb723e4732c5ea80d0d1d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.55.0" ]
revision = "5bc29dc8cdbe07565bdbbcdb2e70824e51eabf26"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.55.0" ]
revision = "59b48f8ac824d7985183ffb3c3174c8caebfef20"
