targets = ["//:circular_buffer"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
version = "1.35.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.35.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.35.0"