manifest = "4de1042129946691d0e8e270705c54e2d466b20c796c3545a676d99e118d3a56"

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
target = "//:concept_check"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw_exception"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.59.0" ]
revision = "b8a861102681be539be9c889cd643986f171c364"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.59.0" ]
revision = "31c92b068bbbe58f7eb52b2076d9c8873bac4b48"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.59.0" ]
revision = "ec90e8c6b2f388644b586d11eb1a3543028fa1f5"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.59.0" ]
revision = "e19e7ba52894c7e2b48d6e344a245e1d58fac51e"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.59.0" ]
revision = "6019dca782a1a7b7e7e105d67216d8f824423101"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.59.0" ]
revision = "73bbb0b61b9d05696252886e840e7f79c14e27ce"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.59.0" ]
revision = "13b0636c0fb5d44a6524daeb2f1f758e901e7260"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.59.0" ]
revision = "767ecdf2c1f31a47d08777feee49062830e97355"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.59.0" ]
revision = "768330940957238cccb17d6e3449f08569656daf"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.59.0" ]
revision = "06f80557aba297b003135535cdc69de522326c50"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.59.0" ]
revision = "7ca2c70ace2cbee01138b0767294887cf34c9c6e"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.59.0" ]
revision = "786cd22e9f5cea81384883b9ea5be6af2dbe322e"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.59.0" ]
revision = "c018d77dfb00804208e6535cc8d99a1daf264ac6"
