manifest = "c4ae3be43de0a20ed267e20c1b82bbc397d7f4f5f665cacd90de18dd62b86cd2"

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
target = "//:concept_check"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.47.0" ]
revision = "33a80f8f05e7f9cafe3856cfd9c9bbbec7229321"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.47.0" ]
revision = "f6585b1993077d3de95ebcf766e3346b8aebb490"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.47.0" ]
revision = "f39e5671b0d09010441b6549031deb68b7c75d44"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.47.0" ]
revision = "cb8e48d0792e765a836b860ca4cd369d614afb36"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.47.0" ]
revision = "5b15e9b0092d3fccfb29c8baa352116f4c4575bd"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.47.0" ]
revision = "b17cd5bfcc8eb6cde44203dde758b9776586a75a"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.47.0" ]
revision = "4c0ca7efafeb92fef2e725bcdebebc4173757633"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.47.0" ]
revision = "f819363b8527a9d718c3f170e44d3a54ed618749"
