manifest = "8a027e7da5066c3e65f72c38735b35b374212e9490c3966e3ae032605abac057"

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
target = "//:concept_check"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.51.0" ]
revision = "fd292a6bc91118aa05094ed4a600d043b9010134"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.51.0" ]
revision = "171d2ac727246bcb7ac5d0b7d008c74a724ed445"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.51.0" ]
revision = "784e15d77cd9f02ee2da75a27e46b50a4343e385"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.51.0" ]
revision = "1308a79340738704252d474ae155b96a13c96463"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.51.0" ]
revision = "f82eeb311d37bd88cd3ae423fd05e6ae7bbb4464"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.51.0" ]
revision = "1e972c8e268661efe8de20c6624cdc88bc8ff634"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.51.0" ]
revision = "ca853bd8456f027d7fc9daa87e616fb7619d94dd"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.51.0" ]
revision = "b5a6046c62682a1174978054789c8cf702a0edea"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.51.0" ]
revision = "eaaaf89177ffc4b769a2e7d4ae33660ca398d913"
