manifest = "3dc3ad3041abedb58b9369b841640ee9310443ee1b6a16f4badebac3563474f4"

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
target = "//:concept_check"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.52.0" ]
revision = "5a7dd9791a79355bedaca141c239cf7328177cc8"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.52.0" ]
revision = "2d6255b8fbd2eec649008975648d95311f698d21"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.52.0" ]
revision = "572e0c8a71b21f0565676a3d4ff91814a8407027"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.52.0" ]
revision = "b26612245d8461fdf35482e38a52d3bba582ac59"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.52.0" ]
revision = "bbd74353a180d11588e21da34f824a43c7e5e402"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.52.0" ]
revision = "ea40e662719516c48040e643b3083c7776941ab6"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.52.0" ]
revision = "5f6617c1b40228007ca57d7f3b011801fe0f6002"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.52.0" ]
revision = "f3e4e9ce56b3553e90055579e84c1b0738dbb25c"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.52.0" ]
revision = "8e193c2456cce1bd79c1525f2d1066b142bf9936"
