targets = [ "//:circular-buffer" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
version = "branch=master"
